### PR TITLE
Do not require enable_dynamic_partitioning for dynamic_partition_append_delimiter_to_record

### PR DESCRIPTION
**Pull request by Tonkonozhenko**

### CODE REVIEW

**Comment by fdmsantos** [comment]
Thanks for this PR. 
It seems now is possible adding new line delimiter without dynamic partitioning. I think that wasn't possible.

**Comment by fdmsantos** [comment]
I have deprecated `dynamic_partition_append_delimiter_to_record` because i think is not makes sense anymore having  the prefix "dynamic_partition". The new variable is `append_delimiter_to_record` .

The Old variable will be removed on next Major Version (4.0.0). 

This PR will be released on version 3.3.0.

**Comment by fdmsantos** [comment]
Thanks  @Tonkonozhenko

**Comment by Tonkonozhenko** [comment]
thank you @fdmsantos !

**Pull request merged**
